<h3>Artes de Pesca</h3>
<fieldset>
    <legend>Cadastro</legend>
          <form>
            <div class="row">
              <div class="large-8 columns">
                <label>Nome da Arte:
                  <input type="text" placeholder="Arte de Pesca" />
                </label>
              </div>
            </div>
            <div class="row">
              <div class="large-4 columns">
                <label>Campos
                  <input type="text" placeholder="large-5.columns" />
                </label>
              </div>
              <div class="large-4 columns">
                <label>Input Label
                  <input type="text" placeholder="large-4.columns" />
                </label>
              </div>
              <div class="large-4 columns">
                <div class="row collapse">
                  <label>Input Label</label>
                  <div class="small-9 columns">
                    <input type="text" placeholder="small-9.columns" />
                  </div>
                  <div class="small-3 columns">
                    <span class="postfix">.com</span>
                  </div>
                </div>
              </div>
            </div>
            <div class="row">
              <div class="large-12 columns">
                <label>Select Box
                  <select>
                    <option value="husker">Husker</option>
                    <option value="starbuck">Starbuck</option>
                    <option value="hotdog">Hot Dog</option>
                    <option value="apollo">Apollo</option>
                  </select>
                </label>
              </div>
            </div>
            <div class="row">
              <div class="large-6 columns">
                <label>Choose Your Favorite</label>
                <input type="radio" name="pokemon" value="Red" id="pokemonRed"><label for="pokemonRed">Red</label>
                <input type="radio" name="pokemon" value="Blue" id="pokemonBlue"><label for="pokemonBlue">Blue</label>
              </div>
              <div class="large-6 columns">
                <label>Check these out</label>
                <input id="checkbox1" type="checkbox"><label for="checkbox1">Checkbox 1</label>
                <input id="checkbox2" type="checkbox"><label for="checkbox2">Checkbox 2</label>
              </div>
            </div>
              <input type="submit" class="button" value="Cadastrar"/>
        </form>
</fieldset>
<div class="row">
      <table class="responsive">
          <thead>
            <tr>
               <th>Nome da Arte</th>
               <th>Pesca Embarcada</th>
               <th>Área de Pesca</th>
               <th></th>
           </tr>
          </thead>
           <tbody>
            <tr>
                <td>Arrasto de Fundo</td>
                <td>Sim</td>
                <td>Mar</td>
                <td><a class="button-small" href=#>Deletar</a></td>
            </tr>
            <tr>
                <td>Calão</td>
                <td>Não/Sim</td>
                <td>Rio/Mar</td>
                <td><a class="button-small" href=#>Deletar</a></td>
            </tr>
            <tr>
                <td>Coleta Manual</td>
                <td>Não/Sim</td>
                <td>Rio/Mar</td>
                <td><a class="button-small" href=#>Deletar</a></td>
            </tr>
            <tr>
                <td>Emalhe</td>
                <td>Não/Sim</td>
                <td>Rio/Mar</td>
                <td><a class="button-small" href=#>Deletar</a></td>
            </tr>
            <tr>
                <td>Jereré</td>
                <td>Célula 10</td>
                <td>Célula 11</td>
                <td><a class="button-small" href=#>Deletar</a></td>
            </tr>
            <tr>
                <td>Groseira/Espinhel</td>
                <td>Célula 10</td>
                <td>Célula 11</td>
                <td><a class="button-small" href=#>Deletar</a></td>
            </tr>
            <tr>
                <td>Linha</td>
                <td>Célula 10</td>
                <td>Célula 11</td>
                <td><a class="button-small" href=#>Deletar</a></td>
            </tr>
            <tr>
                <td>Linha de Fundo</td>
                <td>Célula 10</td>
                <td>Célula 11</td>
                <td><a class="button-small" href=#>Deletar</a></td>
            </tr>
            <tr>
                <td>Manzuá</td>
                <td>Célula 10</td>
                <td>Célula 11</td>
                <td><a class="button-small" href=#>Deletar</a></td>
            </tr>
            <tr>
                <td>Mergulho</td>
                <td>Célula 10</td>
                <td>Célula 11</td>
                <td><a class="button-small" href=#>Deletar</a></td>
            </tr>
            <tr>
                <td>Ratoeira</td>
                <td>Célula 10</td>
                <td>Célula 11</td>
                <td><a class="button-small" href=#>Deletar</a></td>
            </tr>
            <tr>
                <td>Vara de Pesca</td>
                <td>Célula 10</td>
                <td>Célula 11</td>
                <td><a class="button-small" href=#>Deletar</a></td>
            </tr>

           </tbody>
      </table>
</div>