<!doctype html>
<html class="no-js" lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Meu Pescado | Principal</title>
    <link rel="stylesheet" href="css/foundation.css" />
    <script src="js/vendor/modernizr.js"></script>
    <link rel="stylesheet" href="responsive-tables.css" />
    <script src="responsive-tables.js"></script>
  </head>
  <body>
     <div class="fixed">  
     <nav class="top-bar" data-topbar>
        <ul class="title-area">
           
          <li class="name">
            <h1>
              <a href="#">
                Meu Pescado
              </a>
            </h1>
          </li>
          <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
        </ul>
     
        <section class="top-bar-section">
           
          <ul class="left">
            <li class="divider"></li>
            <li class="has-dropdown">
 
           
          </ul>
     
           
          <ul class="right">
            <li class="divider"></li>
            <li class="has-dropdown">
              <a href="#">Main Item 4</a>
              <ul class="dropdown">
                <li><label>Section Name</label></li>
                <li class="has-dropdown">
                  <a href="#" class="">Has Dropdown, Level 1</a>
                  <ul class="dropdown">
                    <li><a href="#">Dropdown Options</a></li>
                    <li><a href="#">Dropdown Options</a></li>
                    <li class="has-dropdown">
                      <a href="#">Has Dropdown, Level 2</a>
                      <ul class="dropdown test">
                        <li><a href="#">Subdropdown Option</a></li>
                        <li><a href="#">Subdropdown Option</a></li>
                        <li><a href="#">Subdropdown Option</a></li>
                      </ul>
                    </li>
                    <li><a href="#">Subdropdown Option</a></li>
                    <li><a href="#">Subdropdown Option</a></li>
                    <li><a href="#">Subdropdown Option</a></li>
                  </ul>
                </li>
                <li><a href="#">Dropdown Option</a></li>
                <li><a href="#">Dropdown Option</a></li>
                <li><label>Section Name</label></li>
                <li><a href="#">Dropdown Option</a></li>
                <li><a href="#">Dropdown Option</a></li>
                <li><a href="#">Dropdown Option</a></li>
                <li><a href="#">See all →</a></li>
              </ul>
            </li>
            <li class="divider"></li>
            <li><a href="#">Main Item 5</a></li>
            <li class="divider"></li>
            <li class="has-dropdown">
              <a href="#">Main Item 6</a>
              <ul class="dropdown">
                <li><a href="#">Dropdown Option</a></li>
                <li><a href="#">Dropdown Option</a></li>
                <li><a href="#">Dropdown Option</a></li>
                <li><a href="#">See all →</a></li>
              </ul>
            </li>
          </ul>
        </section>
      </nav>
     </div>  
      
            <div class="large-3 medium-4 columns">
                <div class="hide-for-small">
                  <h1><img src="http://placehold.it/400x100&text=Logo"/></h1>


                  <ul class="side-nav">
                    <li><a href="#">Section 1</a></li>
                    <li><a href="#">Section 2</a></li>
                    <li><a href="#">Section 3</a></li>
                    <li><a href="#">Section 4</a></li>
                    <li><a href="#">Section 5</a></li>
                    <li><a href="#">Section 6</a></li>
                    <li><a href="#">Section 6</a></li>
                    <li><a href="#">Section 6</a></li>
                    <li><a href="#">Section 6</a></li>
                    <li><a href="#">Section 6</a></li>
                    <li><a href="#">Section 6</a></li>
                  </ul>

                  <p><img src="http://placehold.it/320x240&text=Ad"/></p>

                </div>
            </div>

          <div class="row">    

            <div class="large-9  columns">

              <h2>Page Title <small>Page subtitle</small></h2>

              <p>Bacon ipsum dolor sit amet salami ham hock biltong ball tip drumstick sirloin pancetta meatball short loin. Venison tail chuck pork chop, andouille ball tip beef ribs flank boudin bacon. Salami andouille pork belly short ribs flank cow. Salami sirloin turkey kielbasa. Sausage venison pork loin leberkas chuck short loin, cow ham prosciutto pastrami jowl. Ham hock jerky tri-tip, fatback hamburger shoulder swine pancetta ground round. Tri-tip prosciutto meatball turkey, brisket spare ribs shankle chuck cow chicken ham hock boudin meatloaf jowl.</p>

              <p>Ground round pastrami pork loin tenderloin jerky. Jerky spare ribs biltong, ham hock ham capicola pork. Jerky turducken pork, meatloaf sausage capicola swine corned beef turkey short loin. Tongue prosciutto pork loin, ground round spare ribs venison kielbasa strip steak.</p>

              <p>Hamburger bresaola turkey t-bone, leberkas salami pork chop ham hock beef ribs. Rump biltong meatball venison, short ribs pork loin shank shankle corned beef beef. Cow salami jowl short loin hamburger fatback. Short ribs pork belly shoulder pastrami drumstick salami corned beef ham hock bresaola. Swine filet mignon cow sausage ball tip. Cow ribeye ground round, sausage pork loin pig beef ball tip turkey boudin.</p>

              <p>Prosciutto ball tip filet mignon andouille frankfurter chicken rump sausage meatball. Filet mignon meatloaf ground round andouille ham hock pork. Bresaola short loin meatball chuck hamburger pig. Turkey venison chuck, tongue fatback tail swine jerky corned beef shank kielbasa prosciutto ribeye ham tri-tip. Rump bacon pork belly meatloaf shoulder short loin meatball kielbasa pork loin tongue bresaola brisket corned beef jowl prosciutto. Beef ribs shankle short ribs pork belly corned beef fatback pork chop tongue biltong boudin strip steak sirloin meatloaf pancetta.</p>

            </div>
            
          
<fieldset>
    <legend>Formulários</legend>
          <form>
            <div class="row">
              <div class="large-12 columns">
                <label>Input Label
                  <input type="text" placeholder="large-12.columns" />
                </label>
              </div>
            </div>
            <div class="row">
              <div class="large-4 columns">
                <label>Input Label
                  <input type="text" placeholder="large-4.columns" />
                </label>
              </div>
              <div class="large-4 columns">
                <label>Input Label
                  <input type="text" placeholder="large-4.columns" />
                </label>
              </div>
              <div class="large-4 columns">
                <div class="row collapse">
                  <label>Input Label</label>
                  <div class="small-9 columns">
                    <input type="text" placeholder="small-9.columns" />
                  </div>
                  <div class="small-3 columns">
                    <span class="postfix">.com</span>
                  </div>
                </div>
              </div>
            </div>
            <div class="row">
              <div class="large-12 columns">
                <label>Select Box
                  <select>
                    <option value="husker">Husker</option>
                    <option value="starbuck">Starbuck</option>
                    <option value="hotdog">Hot Dog</option>
                    <option value="apollo">Apollo</option>
                  </select>
                </label>
              </div>
            </div>
            <div class="row">
              <div class="large-6 columns">
                <label>Choose Your Favorite</label>
                <input type="radio" name="pokemon" value="Red" id="pokemonRed"><label for="pokemonRed">Red</label>
                <input type="radio" name="pokemon" value="Blue" id="pokemonBlue"><label for="pokemonBlue">Blue</label>
              </div>
              <div class="large-6 columns">
                <label>Check these out</label>
                <input id="checkbox1" type="checkbox"><label for="checkbox1">Checkbox 1</label>
                <input id="checkbox2" type="checkbox"><label for="checkbox2">Checkbox 2</label>
              </div>
            </div>
            <div class="row">
              <div class="large-12 columns">
                <label>Textarea Label
                  <textarea placeholder="small-12.columns"></textarea>
                </label>
              </div>
            </div>
        </form>
</fieldset>
      
      <table class="responsive">
        <tr>
          <td>Célula 1</td>
          <td>Célula 2</td>
          <td>Célula 3</td>
          <td>Célula 4</td>
        </tr>
        <tr>
          <td>Célula 5</td>
          <td>Célula 6</td>
          <td>Célula 7</td>
          <td>Célula 8</td>
        </tr>
        <tr>
          <td>Célula 9</td>
          <td>Célula 10</td>
          <td>Célula 11</td>
          <td>Célula 12</td>
        </tr>
      </table>
    </div>          
          <footer class="row">
            <div class="large-14 columns">
              <hr/>
              <div class="row">
                <div class="large-6 columns">
                  <p>© Todos os direitos reservados</p>
                </div>
                <div class="large-6 columns">
                  <ul class="inline-list right">
                    <li><a href="#">Bahia Pesca</a></li>
                    <li><a href="#">Isus</a></li>
                    <li><a href="#">Governo do Estado da Bahia</a></li>
                  </ul>
                </div>
              </div>
            </div> 
          </footer>
    </body>
</html>