<?= $this->doctype('XHTML1_TRANSITIONAL') ?>
<html xmlns="http://www.w3.org/1999/xhtml" lang="pt-br">
    <head>
        <meta charset="utf-8" />
        <base href="http://<?= $_SERVER['HTTP_HOST'] . $this->baseUrl() ?>/" />
        <?php
        $this->headLink()->prependStylesheet('css/foundation.css');
        $this->headLink()->appendStylesheet('css/estilo.css');
        $this->headLink()->appendStylesheet('responsive-tables.css');
        $this->headScript()->prependFile('js/jquery-1.10.2.min.js');
        $this->headScript()->appendFile('js/jquery-ui-1.10.3.custom.min.js');
        $this->headScript()->appendFile('js/vendor/modernizr.js');
        $this->headScript()->appendFile('responsive-tables.css');
        echo $this->headLink() . "\n";
        echo $this->headScript() . "\n";
        ?>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Meu Pescado | Principal</title>
    </head>
    <body>
        <div class="fixed">  
            <nav class="top-bar" data-topbar>
                <ul class="title-area">

                    <li class="name">
                        <h1>
                            <a class="meu-pescado" href="#">
                                Meu Pescado
                            </a>
                        </h1>
                    </li>
                    <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
                </ul>
                    <div class="right">
                        <div class="small-4 columns">
                            <input type="text" placeholder="Login" />
                        </div>
                        <div class="small-4 columns">
                             <input type="text" placeholder="Senha" />
                        </div>
                        <div class="small-4 columns">
                            <input class="button small" type="submit" value="Entrar" />
                        </div>
                    </div>
            </nav>
        </div>  

        <div class="large-3 medium-4 columns">
            <div class="hide-for-small">
                <p><a href="<?= $this->url(array("controller" => "index", "action" => "index"), null, true) ?>"><img class="logo" src="img/meu_pescado.jpg"/></a></p>
                <p><a href="http://www.seagri.ba.gov.br/" target="_blank"><img class="logo" src="img/logo_bahia_vert.jpg"/></a></p>
                <p><a href="http://www.bahiapesca.ba.gov.br/" target="_blank"><img class="logo" src="img/bahia_pesca.jpg"/></a></p>
            </div>
        </div>

        <div class="row"> 
            <div id="conteudo">
                <?php echo $this->layout()->content; ?>
            </div>
        </div>
        <footer class="row">
            <div class="large-14 columns">
                <hr/>
                <div class="row" >
                    <div class="large-6 columns">
                        <p>© Todos os direitos reservados</p>
                    </div>
                    <div class="large-6 columns">
                        <ul class="inline-list right">
                            <li><a href="http://www.bahiapesca.ba.gov.br/" target="_blank">Bahia Pesca</a></li>
                            <li><a href="http://www.seagri.ba.gov.br/" target="_blank">Governo do Estado da Bahia</a></li>
                            
                        </ul>
                    </div>
                </div>
            </div> 
        </footer>
    </body>
</html>